### ISSUE TITLE
Support text wrapping

### ISSUE THREAD

**Issue by ziyaddin** [sindresorhus/boxen#16]
Hello, I get a box collapse when I want to print a string longer than the window width. Is it a normal behavior?

### Screenshot:

![image](https://cloud.githubusercontent.com/assets/1016523/20488148/71b330ac-b01f-11e6-8ae0-fa6415c00e8a.png)

### Steps to reproduce:

```js
const boxen = require('boxen');
console.log(boxen('unicornddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', {padding: 1}));
```

**Comment by sindresorhus** [comment]
It doesn't currently support text wrapping. For now you could use [`wrap-ansi`](https://github.com/chalk/wrap-ansi) before passing it to Boxen. I'll leave it open as a feature request. Pull request welcome.

**Comment by Areadrill** [comment]
Hi there, 

I'll be working on a solution for this, probably using the `wrap-ansi` package. If that's okay I'd like to ask a question:

Should the text wrap just enough so that there is no wrap-around, or should it default to a smaller number?

**Comment by LitoMore** [comment]
@Areadrill No wrap-around I think.

Please test the CJK character cases.

Here are some sentences for your test:

**Chinsese**:

```
Apple 员工不只创造产品，他们的奇思妙想更引领着整个行业的潮流。员工多样化的背景带来了思想的碰撞，从令人惊叹的科技到业界领先的环保措施，我们所做的一切都闪耀着他们的灵感与创新。加入 Apple，和我们一道让世界变得更美好。
```

**Japanese**:

```
Appleで働く人々は、ただ製品を作っているだけではありません。あらゆる業界に革命をもたらす、ある種の驚きを生み出しています。驚異的なテクノロジーの開発から業界をリードする環境への取り組みまで、私たちのすべての活動に革新をもたらすのは、多様な人々と彼らが生み出す多彩なアイデアです。あなたもAppleに参加し、協力してください。出会った時よりも良い世界を、未来に渡すために。
```

**Korean**:

```
Apple 직원들이 만드는 것은 제품만이 아닙니다. 산업 전반을 송두리째 바꾸는 기적을 창조해내죠. 놀라운 기술 개발에서 업계를 주도하는 환경 보호 노력에 이르기까지, Apple이 하는 모든 일의 이면에는 혁신이 살아 숨쉬고 있습니다. 그 혁신을 뒷받침하는 것이 바로 구성원들의 다양성과 아이디어죠. Apple의 일원이 되어, 더 살기 좋은 세상을 만드는 이 위대한 여정에 동참해보세요.
```

**Comment by Areadrill** [comment]
In light of issue #35, which directly impacts my solution since I'm using `wrap-ansi` on strings which might have ANSI styles applied, should I come up with a way to rectify the string's formatting post-split? 

I ask because chalk might not be the only relevant use case and if that's so, a more generic fix should probably be applied.

**Comment by Areadrill** [comment]
Hi again! My solution is pretty much good to go, with ANSI codes being correctly split and everything but I have one last question: How do I write tests for this?

This particular package is dependent on the size of the window it is run on. Even the tests that are currently implemented will fail if you make a small enough window, so testing for a test case where the content is supposed to wrap would, again, depend on the size of the window.
