### ISSUE TITLE
Problem with emoji sizes

### ISSUE THREAD

**Issue by Offirmo** [sindresorhus/boxen#24]
Boxen is amazing but has troubles with emojis.

I tried to devise a PR myself, but apparently it's in a sub-sub dependency, so you'll be faster than me at fixing it:

<img width="189" alt="capture d ecran 2017-06-28 a 22 31 23" src="https://user-images.githubusercontent.com/603503/27658807-8b258470-5c51-11e7-8157-449998ed8798.png">

I enclosed the strings with `"` to ensure it was not from my side.
Here is the text for reproducing:
```
🙂  CHARACTERISTICS 💗
"👶🏽  level.........1"
"💗  health........1"
"💙  mana..........0"
"🏋🏽  strength......1"
"🤸🏽  agility.......1"
"🏊🏽  vitality......1"
"👵🏽  wisdom........1"
"🤹🏼‍♀️  luck..........1"
```

**Comment by Offirmo** [comment]
I used the latest iTerm on macOs. The standard terminal app has the same problem:

<img width="196" alt="capture d ecran 2017-06-28 a 22 30 43" src="https://user-images.githubusercontent.com/603503/27658786-72bfee5c-5c51-11e7-85e4-a8237ce3888d.png">

**Comment by Offirmo** [comment]
I really need this for a pet project. I'm starting working on it.

**Comment by kevva** [comment]
Sounds like it's related to https://github.com/sindresorhus/string-width/issues/2.

**Comment by Offirmo** [comment]
Figured it out. I'm working on is-fullwidth-code-point and string-width but that's SUPER HARD !!!

**Comment by Offirmo** [comment]
This is insanely hard, but PRs coming soon.

**Comment by Offirmo** [comment]
See also: https://gitlab.com/gnachman/iterm2/issues/5293

**Comment by Offirmo** [comment]
Progress so far:

<img width="208" alt="screen shot 2017-09-25 at 10 02 05" src="https://user-images.githubusercontent.com/603503/30798853-57ef6234-a21e-11e7-8101-5eb60e9a292b.png">

**Comment by LinusU** [comment]
I think that the behaviour might have changed between macOS Sierra and High Sierra. I saw the same thing in one of my projects here: LinusU/emoji-commit#6

**Comment by Offirmo** [comment]
@LinusU thanks for sharing. Unicode 9 introduced full/half width emojis, that feature may have landed in High Sierra.

**Comment by Offirmo** [comment]
Sindre didn't answer to my PRs and I lost interest. Sorry guys. Maybe at a later time.

**Comment by screendriver** [comment]
@sindresorhus any updates regarding emoji support in `boxen`?

**Comment by sindresorhus** [comment]
This is how it looks in the latest `boxen` and iTerm2. Almost:

<img width="293" alt="Screen Shot 2019-05-29 at 21 41 34" src="https://user-images.githubusercontent.com/170270/58566287-8a45ab80-825a-11e9-91c5-39e61ed5bf0e.png">

**Comment by Offirmo** [comment]
Yes, it's depending on the level of unicode support from the underlying platform.

While I believe there are ways to improve boxen and string-width behavior, this will never work perfectly. I agree that the return-on-investment is not worth it.
