### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by leebenson** [sindresorhus/boxen#32]
Any plans for TS support?

**Comment by SamVerschueren** [comment]
Feel free to create them yourself and publish to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide

**Comment by MrTarantula** [comment]
See #39.
