### ISSUE TITLE
Feature Request: Global setting

### ISSUE THREAD

**Issue by mgreci** [sindresorhus/boxen#38]
Is there an easy way to set boxen's style object once and no longer need to pass the style object every time I use boxen()?

**Comment by sindresorhus** [comment]
"Global settings" is a bad idea as it would affect other modules using Boxen too. We could add a constructor that created new Boxen instances, but I don't really see the point as you can easily just create your own wrapper. This problem applies to pretty much any type of module that accept options and it would be weird if all modules would need a constructor thingy.

Just as easy as:

```js
const customBoxen = (input, options) => boxen(input, {
	...options,
	borderStyle: 'double' // Custom default
});

customBoxen('foo', {borderColor: 'blue'});
```
