### ISSUE TITLE
Extend backgroundColor to under the border

### ISSUE THREAD

**Issue by Zireael** [sindresorhus/boxen#44]
Hi, when I specify the `backgroundColor`, it is applied only immediately just under the thext inside the box. But then there is a black moat between the text and the border, like this:
![image](https://user-images.githubusercontent.com/3856578/66699701-d7de2480-ece0-11e9-84ad-8603c45d66b5.png)

To achieve something like this:
![image](https://user-images.githubusercontent.com/3856578/66699799-a31e9d00-ece1-11e9-9490-d752766edb5e.png)

This is under Windows cmd terminal, so maybe the background gets rendered better in other terminals. Also, I suspect putting bacground to fill inside of the box might not be possible as adding background color to border glyphs would spill that colour to outside the box as well?

Lastly, I know this is not core functionality of boxen, but consider adding a simple option to change text color. Can be achieved with Chalk etc, but for anyone needing a one dependency solution this might be enough..
```
const boxen = require("boxen");
const color = require("chalk");
console.log(
  boxen(color.hex("#07171d")("this is some text"), {
    margin: { top: 1, right: 0, bottom: 1, left: 2 },
    padding: { top: 0, right: 2, bottom: 0, left: 2 },
    borderColor: "#e29578",
    backgroundColor: "#e0f0f5",
    borderStyle: "double",
  })
);
```

**Comment by sindresorhus** [comment]
> Also, I suspect putting bacground to fill inside of the box might not be possible as adding background color to border glyphs would spill that colour to outside the box as well?

Correct.

> but consider adding a simple option to change text color.

Sure, I agree that could be useful.

**Comment by sindresorhus** [comment]
The background looks better on iTerm on macOS:

<img width="177" alt="Screenshot 2020-02-12 at 19 51 57" src="https://user-images.githubusercontent.com/170270/74336605-2b689800-4dd1-11ea-8715-9b9405b59d55.png">

**Comment by sindresorhus** [comment]
I would recommend trying out https://github.com/microsoft/terminal. It might look better there.
