### ISSUE TITLE
Boxen colors don't get saved to console logs

### ISSUE THREAD

**Issue by Zireael** [sindresorhus/boxen#45]
I suspect this stems from how boxen core functionality and actually in some cases is preferred way of working. Just wanted to report/point out that boxen `borderColor` and `backgroundColor` values don't get saved to console text log files when using pm2process manager. However Chalk does put those colour strings with text, so that when the logs are later reviewed with `pm2 --logs`, the colours are displayed. What worries me, if I wrap a chalk-coloured string inside boxen, the chalk colours get stripped out as well. The first box has text colour changed to blue through Chalk library. Notice at the bottom of screenshot that two Chalk strings not wrapped in boxen get displayed with colours.

console.log displayed back in terminal:
![image](https://user-images.githubusercontent.com/3856578/66700149-6e144980-ece5-11e9-9ab3-58eaa90e2a8a.png)

From original:
![image](https://user-images.githubusercontent.com/3856578/66700203-0b6f7d80-ece6-11e9-841f-5fb5a7c0b2c5.png)

Could you add a settings toggle to let users decide whether boxen strips colours from output strings or not? Unless I'm misunderstanding and this is an issue with how pm2 saves process console logs to file.

```js
const boxen = require("boxen");
const color = require("chalk");

console.log(
  boxen(color.hex("#007ea8")("Results Monitor server is running"), {
    margin: {top:1, right:0, bottom:1, left:2},
    padding: {top:0, right:2, bottom:0, left:2},
    // dimBorder: false,
    borderColor: "#023255",
    backgroundColor: "#010c14",
    borderStyle: "double", 
  })
);
console.log(
  boxen(color.hex("#07171d")("this is some text"), {
    margin: { top: 1, right: 0, bottom: 1, left: 2 },
    padding: { top: 0, right: 2, bottom: 0, left: 2 },
    borderColor: "#e29578",
    backgroundColor: "#e0f0f5",
    borderStyle: "double",
  })
);
console.log(color.bgHex("#e8edde").hex("#000214")("qPCR Monitor is running"));
console.log(color.bgHex("#d0dcd6").hex("#000214")(`Observing folder: ${entry}`));
```

**Comment by sindresorhus** [comment]
Are you using Chalk v3? The behavior should be the same if you're using the same Chalk version as Boxen.
