### ISSUE TITLE
Problem with BorderStyle

### ISSUE THREAD

**Issue by j2pb** [sindresorhus/boxen#47]
`import * as boxen from 'boxen';`

` console.log(boxen("text", { padding: 1, margin: 1, borderStyle: 'double'}));`

returns

 ....Type '"double"' is not assignable to type 'BorderStyle | CustomBorderStyle'.

**Comment by sindresorhus** [comment]
The answer is easily discoverable if you spend just a little bit of time debugging.

https://github.com/sindresorhus/boxen/blob/c5776208a5aebd4883e9b06683710a3a19fb979f/index.test-d.ts#L24

**Comment by Stijnkool** [comment]
Am I correct to say that when using const enums for `BorderStyle`, typescript projects compiled with the --isolatedModules flag will not be able to use `BorderStyle`? I think --isolatedModules is sort of required when compiling with babel.

For example, I get the following error when trying to access BorderStyle:
`Cannot access ambient const enums when the '--isolatedModules' flag is provided.ts(2748)`

Am I missing something?
