### ISSUE TITLE
Do you mind if I do some code refactoring?

### ISSUE THREAD

**Issue by entrywayaudibly** [sindresorhus/boxen#48]
I think this library could benefit from code refactoring.

I wouldn't open a PR for anything that makes breaking changes. Just clearer code.

**Comment by sindresorhus** [comment]
Every refactor risks breaking something that is not covered by tests, so I'm going to say yes if you also add more tests.

**Comment by sindresorhus** [comment]
Closing as nothing happened here, but refactoring is still welcome.
