### ISSUE TITLE
Border style type issue

### ISSUE THREAD

**Issue by vinaysharma14** [sindresorhus/boxen#49]
**Version:**
^4.2.0

**Issue:** 
The `borderStyle` option throws type error in TypeScript `^4.1.2`. None of these seem to work: `single`, `double`, `round`, `bold`, `singleDouble`, `doubleSingle`, `classic`.

**Screenshot**:

<img width="1213" alt="Screenshot 2020-12-26 at 2 15 15 PM" src="https://user-images.githubusercontent.com/48080660/103148409-5360b000-4785-11eb-92db-52fcb0158cae.png">

**Comment by sindresorhus** [comment]
It's an enum in TS. Look at https://github.com/sindresorhus/boxen/blob/master/index.d.ts

**Comment by vinaysharma14** [comment]
@sindresorhus so how would you suggest to pass the value then? The app won't compile due to this error.

**Comment by sindresorhus** [comment]
Look at the type tests. You just use it like any TS enum.

**Comment by vinaysharma14** [comment]
Well, the screenshot above literally uses the code snippet from the usage in readme. How else am I supposed to use it?
```
console.log(boxen('unicorn', { padding: 1, margin: 1, borderStyle: 'double' }));
```

**Comment by vinaysharma14** [comment]
By types tests you mean [this file](https://github.com/sindresorhus/boxen/blob/master/test.js), right? Well, the screenshot above literally uses the code snippet from the usage in readme. How else am I supposed to use it?
```
console.log(boxen('unicorn', { padding: 1, margin: 1, borderStyle: 'double' }));
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/boxen/releases/tag/v5.0.0 :)
