### ISSUE TITLE
Multiple boxes on same line (feature request)

### ISSUE THREAD

**Issue by jbakchr** [sindresorhus/boxen#55]
Personally I really, really like this package :)

It would, however, be really cool if the package had the possibility of printing multiple boxes on the same line. Could be cool to use for simple terminal games (like tic tac toe) or something like that :)

Here's a (really) quick example of how I that might look:

<img width="112" alt="Screenshot 2021-06-14 at 12 21 09" src="https://user-images.githubusercontent.com/21309287/121877605-14122580-cd0b-11eb-8008-6a9f8462635e.png">

Hope this ("feature request") makes sense :) Just a thought at least.

Br, Jonas

**Comment by sindresorhus** [comment]
I'm unfortunately going to pass on this. While, I agree, it could be useful in some cases, the majority of use-cases do not need multiple boxes. Also, adding support for this would make the codebase a lot more complicated, and it's already hard enough to maintain.

For multiple boxes, I would recommend trying out  https://github.com/vadimdemedes/ink It makes it a lot easier to implement stuff like this.

**Comment by jbakchr** [comment]
I fully understand and just wanted to give some input as to what might be a cool addition to your package 😃

But I understand. And thanks for a cool package anyway 😃
