### ISSUE TITLE
cropping leading whitespace in new version ??

### ISSUE THREAD

**Issue by eswat2** [sindresorhus/boxen#62]
i have an npx business card that's built on boxen.  When i use boxen@5.0.1 it displays leading whitespace in the strings, for example:

npx eswat2@2.2.110

However, if i build with the latest version (boxen@5.1.1), it displays without any leading whitespace:

npx eswat2@2.1.108

Has anyone else notice this problem ??

**Comment by eswat2** [comment]
you can find the code for this here, if you want to try it locally -- https://github.com/eswat2/eswat2

the following command will build and display the card locally:

yarn dev

**Comment by Caesarovich** [comment]
Opening a Pull Request fixing this.

**Comment by eswat2** [comment]
thank you !!
