### ISSUE TITLE
require() of ES Module not supported. With Typescript 4.6 and boxen 6.0.0 or higher.

### ISSUE THREAD

**Issue by v1ern3s** [sindresorhus/boxen#76]
Downgrading the package version to 5.1.2 fix it.

[replit example](https://replit.com/@aaronjaimes/BoxenTypescriptBug?v=1)

**COMPLETE LOG**
`require() of ES Module project\node_modules\boxen\index.js from project\file.ts not supported. Instead change the require of index.js in project\file.ts to a dynamic import() which is available in all CommonJS modules.`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

And you will need TypeScript 4.7.
