### ISSUE TITLE
Newlines get stripped out

### ISSUE THREAD

**Issue by gandalf3** [sindresorhus/boxen#79]
When the width of the box (including margin) exceeds the number of available columns (which defaults to 80 if it cannot be detected), the box is rendered without any newlines. This causes lots hard-to-read output from clients which don't set a width ([such as serverless-offline](https://github.com/dherault/serverless-offline/blob/b44cf07c57a3fe10e47e5e9a0ee762fb281f8aa9/src/utils/logRoutes.js#L41)) seemingly(?) no reason.
```
┌──────────────────────────────────────────────────────────────────────────────┐│                                                                              ││   GET | http://localhost:3000/dev/namespace-export-1                         ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/namespaceExport1/invocations    ││   GET | http://localhost:3000/dev/namespace-export-2                         ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/namespaceExport2/invocations    ││   GET | http://localhost:3000/dev/namespace-export-3                         ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/namespaceExport3/invocations    ││   GET | http://localhost:3000/dev/namespace-export-4                         ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/namespaceExport4/invocations    ││   GET | http://localhost:3000/dev/js-extension                               ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/js-extension/invocations        ││   GET | http://localhost:3000/dev/cjs-extension                              ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/cjs-extension/invocations       ││   GET | http://localhost:3000/dev/package-type                               ││   POST |                                                                     ││   http://localhost:3000/2015-03-31/functions/package-type/invocations        ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
```
This occurs extra often as the [margin-shrinking logic](https://github.com/sindresorhus/boxen/blob/main/index.js#L305) will at most shrink `options.width` to `columns - BORDERS_WIDTH`, in which case [this conditional](https://github.com/sindresorhus/boxen/blob/main/index.js#L221) is still guaranteed to be true, causing newlines to be removed.

Maybe I'm misunderstanding but is there any particular reason for stripping out newlines if the box would be too wide? I feel like the result is less readable than if it were just left up to the terminal to wrap or truncate lines.

**Comment by yannbf** [comment]
I second this, we're using this library in Storybook and we love it, but the result in CI is very tough to read, and the content gets a little messy when the users resize their terminal:
![2022-12-16 13 56 24](https://user-images.githubusercontent.com/1671563/208103452-9a8e4e49-d62e-43c8-8b6a-3552a01d0948.gif)

However, if there is always a new line, the result is perfect:
![2022-12-16 13 57 36](https://user-images.githubusercontent.com/1671563/208103519-80b15065-a873-4b34-bc53-29105a7e53d2.gif)

**Comment by yannbf** [comment]
Additionally, we are also using boxen to visualize the terminal output in Storybook, so we can get visual regression and demo benefits. 

Unfortunately, given that the newlines are not present, it looks really off:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1671563/208104067-3d9339b0-b9c5-40c1-86c4-f5e8d719ed0f.png">


If I make changes in the boxen source to always include new lines, it looks pretty cool:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/1671563/208103766-3cc67eef-7579-406c-9c22-a16223917572.png">

**Comment by Caesarovich** [comment]
New version will be out soon, stay tuned @yannbf and @gandalf3 . By the way Storybooks looks awesome I need to get a look into it ;)

**Comment by yannbf** [comment]
oh my gosh this is perfect!! thank you so so much @Caesarovich !! I'll make sure to prepare that Storybook and make it available, showing the awesomeness of boxen 🙆

**Comment by ndelangen** [comment]
@yannbf I had no reason to push this before: https://github.com/storybookjs/storybook/pull/20134

But now there might be a need to merge this soon?
So that we can start using ESM-only packages in core-server?

**Comment by Caesarovich** [comment]
https://github.com/sindresorhus/boxen/releases/tag/v7.0.1 version 7.0.1 is now out !

Thanks for the support and the interest shown in boxen  @yannbf :)

Boxen has already moved to ESM if that was your concern @ndelangen 

I'll close this issue now, we'll wait for the feedback
