### ISSUE TITLE
boxen is not working

### ISSUE THREAD

**Issue by Shani-Sinojiya** [sindresorhus/boxen#87]
![image](https://user-images.githubusercontent.com/72117665/226977955-af0d3d91-6f2a-463a-b37b-f53378318bcd.png)

**Comment by Caesarovich** [comment]
That doesn't look like it has anything to do with boxen. At best I'd guess you tried to use require() inside an ES module to import boxen.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
