### ISSUE TITLE
How would you go about centering a box?

### ISSUE THREAD

**Issue by saelfaer** [sindresorhus/boxen#9]
I'm not sure it is even possible but It would be nice to have a property to center the box on screen.

**Comment by SamVerschueren** [comment]
If Sindre is ok with the feature, the [cli-width](https://www.npmjs.com/package/cli-width) package can be used. Not sure in which cases you want to use that though. Any ideas @saelfaer ?

**Comment by sindresorhus** [comment]
> If Sindre is ok with the feature, the cli-width package can be used.

Or even better, just `process.stdout.columns`.

**Comment by SamVerschueren** [comment]
> Or even better, just `process.stdout.columns`.

Cool! Thanks for the tip :).

**Comment by sindresorhus** [comment]
Check out the `--center` flag in boxen-cli 0.5.0 ;)
