### ISSUE TITLE
import problem with 7.1.1

### ISSUE THREAD

**Issue by hstaudacher** [sindresorhus/boxen#92]
After updating to boxen 7.1.1 we see the following error when executing our app.

```sh
/.../node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /.../node_modules/boxen/index.js from /.../app.ts not supported.
Instead change the require of index.js in /.../app.ts to a dynamic import() which is available in all CommonJS modules.
```

Our code imports boxen like this:

```ts
import boxen from 'boxen';
```

We use `ts-node` to run the app.

**Comment by sindresorhus** [comment]
This is a problem with `ts-node`, not this package. I recommend using `tsx` instead.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
