### ISSUE TITLE
Replace chalk with picocolors

### ISSUE THREAD

**Issue by boehs** [sindresorhus/boxen#95]
Picocolors is both faster and about 6.9% of the size of chalk. There is a quite simple migration guide [here](https://github.com/alexeyraspopov/picocolors?tab=readme-ov-file#replacing-chalk)

**Comment by sindresorhus** [comment]
You are wasting both your and maintainers' time on this meaningless effort. The performance difference between Picocolors and Chalk is meaningless in real-world situations. Don't fall for syntethic benchmarks that do not reflect real-world usage. The file size difference also does not matter. Chalk and Picocolors are not used in the browser and 30 kB difference on disk does not make any difference. Chalk also brings a bunch of benefits and better API. In addition, it's likely Chalk is already in the dependency tree, so the Chalk is actually 100% smaller than Picocolors.
