### ISSUE TITLE
8.0 will expose ExperimentalWarning while use node 20+

### ISSUE THREAD

**Issue by tianyingchun** [sindresorhus/boxen#98]
(node:60053) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

node : v20.12.2

**Comment by Caesarovich** [comment]
Hi, I  reproduced issue with Node v21.6.2 as well as Node v22.4.1. I ran `example.js` to test this.

This warning has been in node for a long time (https://github.com/nodejs/node/issues/51347). Perhaps it will finally disappear at Node 23/24 but for now that's how it is. 

As the devs of `boxen` we cant do much about it as it seems this warning comes from a dependency of the project.

**Comment by tianyingchun** [comment]
We can removes cli-boxes dependent

**Comment by tianyingchun** [comment]
https://github.com/sindresorhus/cli-boxes/issues/11

**Comment by Caesarovich** [comment]
Well no, boxen depends on that package for a reason. It's what provides the different box styles. You can create an issue upstream but sadly that won't be changed here.

**Comment by fregante** [comment]
This was fixed in 8.0.1

-  https://github.com/sindresorhus/boxen/pull/102
